# Generated by Django 2.2.2 on 2019-07-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('scamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.SCAModel')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'db_table': 'service_type',
                'ordering': ['-id'],
            },
            bases=('service.scamodel',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('scamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.SCAModel')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'shop',
            },
            bases=('service.scamodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('scamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service.SCAModel')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('license_plate', models.CharField(max_length=15)),
                ('service_types', models.ManyToManyField(related_name='services', to='service.ServiceType', verbose_name='Service Types')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
                'ordering': ['-date_created', '-time_created'],
            },
            bases=('service.scamodel',),
        ),
    ]
