# Generated by Django 2.2.2 on 2019-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['-id'], 'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type_id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_types',
            field=models.ManyToManyField(related_name='services', to='service.ServiceType', verbose_name='Service Type'),
        ),
    ]
